### ISSUE TITLE
Missing APR in LAPIS-CELO pool

### ISSUE THREAD

**Issue by BriungRi** [Ubeswap/ubeswap-interface#252]
The LAPIS-CELO pool doesn't reward UBE. Instead, it rewards LAPIS tokens.

I added the LAPIS-CELO pool without supporting APRs, and you can see my (terrible) handiwork in these lines:
https://github.com/Ubeswap/ubeswap-interface/blob/664567b464e161b86e1dd561aa04d9270dcd0312/src/state/stake/hooks.ts#L257-L260

where I set `ubePerYear` to 0 if the reward token is not UBE. Instead, we should generalize `ubePerYear` to `dollarsPerYear` and calculate it based on the current price of the `rewardToken`.

**Comment by randyn** [comment]
I'll take a look
