### ISSUE TITLE
Loading issue with the farm page.

### ISSUE THREAD

**Issue by TanishKhanna19** [Ubeswap/ubeswap-interface#423]
![photo_2021-12-07_00-34-50](https://user-images.githubusercontent.com/95648029/144906516-7e6bebfe-c355-4805-b830-25f39a699582.jpg)
Many users have reported issues loading the farm page with metamask mobile, chrome, and other browsers.
So far I have looked at this issue, as per the user's response I think it's related to the latest version of browsers. The Farm page just keeps loading in mobile, shows an error in desktop browsers for the latest version but it works well with older versions of chrome, opera, and other browsers.

**Comment by aaronmgdr** [comment]
@BriungRi  you fixed this i believe with https://github.com/Ubeswap/ubeswap-interface/commit/a32422a40f09a44ac5e7ab8704aa8b4f1fd9d4e7
