### ISSUE TITLE
Tripple Rewards display mismatched

### ISSUE THREAD

**Issue by aaronmgdr** [Ubeswap/ubeswap-interface#428]
**Bug Description**
Sometimes the earned rewards shown are displayed alongside the wrong token

**Steps to Reproduce**

This seems to only affect triple reward pools 

go to manage page of a tripple reward pool

note its not always wrong 

when claiming rewards are correct

**Expected Behavior**

When I have three types of rewards the rewards on a line should be for the token symbol on the same line. 

**Additional Context**

**Comment by BriungRi** [comment]
Addressed by https://github.com/Ubeswap/ubeswap-interface/pull/472
